SELECT 
    t1.COLUMN_NAME,
    t1.COLUMN_TYPE AS db1_type,
    t2.COLUMN_TYPE AS db2_type,
    CASE 
        WHEN t2.COLUMN_NAME IS NULL THEN 'Missing in db2'
        WHEN t1.COLUMN_NAME IS NULL THEN 'Missing in db1'
        WHEN t1.COLUMN_TYPE <> t2.COLUMN_TYPE THEN 'Type mismatch'
        ELSE 'Match'
    END AS difference
FROM (
    SELECT COLUMN_NAME, COLUMN_TYPE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'db1' AND TABLE_NAME = 'table1'
) t1
LEFT JOIN (
    SELECT COLUMN_NAME, COLUMN_TYPE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'db2' AND TABLE_NAME = 'table2'
) t2
ON t1.COLUMN_NAME = t2.COLUMN_NAME

UNION ALL

SELECT 
    t2.COLUMN_NAME,
    t1.COLUMN_TYPE AS db1_type,
    t2.COLUMN_TYPE AS db2_type,
    'Missing in db1' AS difference
FROM (
    SELECT COLUMN_NAME, COLUMN_TYPE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'db2' AND TABLE_NAME = 'table2'
) t2
LEFT JOIN (
    SELECT COLUMN_NAME, COLUMN_TYPE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'db1' AND TABLE_NAME = 'table1'
) t1
ON t1.COLUMN_NAME = t2.COLUMN_NAME
WHERE t1.COLUMN_NAME IS NULL;
